### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by mattwright324**
- Changes for YouTube API Periodic Audit
  - Replace the likes icon with the word 'likes'
  - Remove the CSV/JSON export button option
  - Remove custom displayed stat comparing downloaded comment count with total video comment count
  - Force user decision to delete or refresh group if data is older than 30 days
- Cleanup for broken and API deprecated features
  - Remove account sign-in (hasn't worked for a long time)
  - Remove anything related to dislikes (removed in 2021)

### CODE REVIEW

**Comment by greatkeke** [comment]
Hi matt, thanks for your great job. But why `export` was removed? I think this function is very useful.

**Comment by greatkeke** [comment]
Maybe you want to create something new to replace 'export'?

**Comment by mattwright324** [comment]
Hi @greatkeke 

Unfortunately it had to be removed due to a YouTube terms of service audit, same reason I had to remove it from my web tools

https://github.com/mattwright324/youtube-metadata/discussions/150

**Comment by greatkeke** [comment]
Ok, got it. Thanks a lot again.

**Pull request merged**
